### ISSUE TITLE
[BUG] Short Description

### ISSUE THREAD

**Issue by nickstrijbos** [airpodsreplicas/airreps#51]
### Current Behavior

Max Volume on MacBook Pro with AirPods Pro Gen 2 5.2TB with version 31.6.505.23. No update on CloudCC or FlyCC saw a lot of issues when initially searching for it online after I noticed it. But nothing to be seen on the site. 

### Expected Behavior

Volume control on the MacBook as usual with headphones. 

### Steps To Reproduce

1. Just connect them as per instructions.
2. Volume control doesn't work and music blasts at 100% volume

### Screenshots and Additional Info

MacBook version: 14.2.1

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.

**Comment by TowyTowy** [comment]
This is for reporting bugs on the guide, not issues with your AirPods. Closing this issue.

**Comment by nickstrijbos** [comment]
It is essentialy a bug on the guide? Because I bought them knowing that they work on a MacBook. So I would like to see a disclaimer on the version 5.2TB that you could experience issues with volume. Otherwise I would have looked at a different version. But since it is not visible on the guide. And multiple people say it's not working even going back 5 months ago.
